db-host : localhost
db-port : 5432
db-protocol : jdbc:postgresql
db-schema : demodb
spring :
    application :
        name : MYBATIS SAMPLE APP
    datasource :
        driver-class-name : org.postgresql.Driver
        url : ${db-protocol}://${db-host}:${db-port}/${db-schema}
        username : postgres
        password : mysecretpassword
    h2 :
        console :
            enabled : true
    liquibase :
        change-log : classpath:db/changelog/db.changelog-hub.xml
        default-schema : public
        drop-first : false
        enabled : true
        password : ${spring.datasource.password}
        url : ${spring.datasource.url}
        user : ${spring.datasource.username}
