jwt:
    auth:
        converter:
            principal-attribute: preferred_username
            resource-id: city-api
server:
    port: 8080
    servlet:
        context-path: /
#    security:
#        oauth2:
#            client:
#                provider:
#                    keycloak:
#                        issuer-uri: http://localhost:9200/auth/realms/city-api
#                        user-name-attribute: preferred_username
#                registration:
#                    keycloak:
#                        authorization-grant-type: authorization_code
#                        client-id: city-api
#                        scope: openid
#            resource-server:
#                jwt:
#                    issuer-uri: http://localhost:9200/realms/city-api
#                    jwk-set-uri: ${spring.security.oauth2.resource-server.jwt.issuer-uri}/protocol/openid-connect/certs
