# db with postgres engine secret configuration
db.secret {
  # db with postgres engine host secret
  host = "localhost"
  # db with postgres engine port secret
  port = 5432
  # db with postgres engine protocol secret
  protocol = "jdbc:postgresql"
  # db with postgres engine schema secret
  schema = "demodb"
  # db with postgres engine username secret
  username = "postgres"
  # db with postgres engine password secret
  password = "mysecretpassword"
}